//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rollout.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0002
    {
        public string NNSY { get; set; }
        public string NNUD01 { get; set; }
        public string NNUD02 { get; set; }
        public string NNUD03 { get; set; }
        public string NNUD04 { get; set; }
        public string NNUD05 { get; set; }
        public string NNUD06 { get; set; }
        public string NNUD07 { get; set; }
        public string NNUD08 { get; set; }
        public string NNUD09 { get; set; }
        public string NNUD10 { get; set; }
        public Nullable<double> NNN001 { get; set; }
        public Nullable<double> NNN002 { get; set; }
        public Nullable<double> NNN003 { get; set; }
        public Nullable<double> NNN004 { get; set; }
        public Nullable<double> NNN005 { get; set; }
        public Nullable<double> NNN006 { get; set; }
        public Nullable<double> NNN007 { get; set; }
        public Nullable<double> NNN008 { get; set; }
        public Nullable<double> NNN009 { get; set; }
        public Nullable<double> NNN010 { get; set; }
        public string NNCK01 { get; set; }
        public string NNCK02 { get; set; }
        public string NNCK03 { get; set; }
        public string NNCK04 { get; set; }
        public string NNCK05 { get; set; }
        public string NNCK06 { get; set; }
        public string NNCK07 { get; set; }
        public string NNCK08 { get; set; }
        public string NNCK09 { get; set; }
        public string NNCK10 { get; set; }
    }
}
