//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rollout.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0101
    {
        public double ABAN8 { get; set; }
        public string ABALKY { get; set; }
        public string ABTAX { get; set; }
        public string ABALPH { get; set; }
        public string ABDC { get; set; }
        public string ABMCU { get; set; }
        public string ABSIC { get; set; }
        public string ABLNGP { get; set; }
        public string ABAT1 { get; set; }
        public string ABCM { get; set; }
        public string ABTAXC { get; set; }
        public string ABAT2 { get; set; }
        public string ABAT3 { get; set; }
        public string ABAT4 { get; set; }
        public string ABAT5 { get; set; }
        public string ABATP { get; set; }
        public string ABATR { get; set; }
        public string ABATPR { get; set; }
        public string ABAB3 { get; set; }
        public string ABATE { get; set; }
        public string ABSBLI { get; set; }
        public Nullable<decimal> ABEFTB { get; set; }
        public Nullable<double> ABAN81 { get; set; }
        public Nullable<double> ABAN82 { get; set; }
        public Nullable<double> ABAN83 { get; set; }
        public Nullable<double> ABAN84 { get; set; }
        public Nullable<double> ABAN86 { get; set; }
        public Nullable<double> ABAN85 { get; set; }
        public string ABAC01 { get; set; }
        public string ABAC02 { get; set; }
        public string ABAC03 { get; set; }
        public string ABAC04 { get; set; }
        public string ABAC05 { get; set; }
        public string ABAC06 { get; set; }
        public string ABAC07 { get; set; }
        public string ABAC08 { get; set; }
        public string ABAC09 { get; set; }
        public string ABAC10 { get; set; }
        public string ABAC11 { get; set; }
        public string ABAC12 { get; set; }
        public string ABAC13 { get; set; }
        public string ABAC14 { get; set; }
        public string ABAC15 { get; set; }
        public string ABAC16 { get; set; }
        public string ABAC17 { get; set; }
        public string ABAC18 { get; set; }
        public string ABAC19 { get; set; }
        public string ABAC20 { get; set; }
        public string ABAC21 { get; set; }
        public string ABAC22 { get; set; }
        public string ABAC23 { get; set; }
        public string ABAC24 { get; set; }
        public string ABAC25 { get; set; }
        public string ABAC26 { get; set; }
        public string ABAC27 { get; set; }
        public string ABAC28 { get; set; }
        public string ABAC29 { get; set; }
        public string ABAC30 { get; set; }
        public string ABGLBA { get; set; }
        public Nullable<double> ABPTI { get; set; }
        public Nullable<decimal> ABPDI { get; set; }
        public string ABMSGA { get; set; }
        public string ABRMK { get; set; }
        public string ABTXCT { get; set; }
        public string ABTX2 { get; set; }
        public string ABALP1 { get; set; }
        public string ABURCD { get; set; }
        public Nullable<decimal> ABURDT { get; set; }
        public Nullable<double> ABURAT { get; set; }
        public Nullable<double> ABURAB { get; set; }
        public string ABURRF { get; set; }
        public string ABUSER { get; set; }
        public string ABPID { get; set; }
        public Nullable<decimal> ABUPMJ { get; set; }
        public string ABJOBN { get; set; }
        public Nullable<double> ABUPMT { get; set; }
        public string ABPRGF { get; set; }
        public string ABSCCLTP { get; set; }
        public string ABTICKER { get; set; }
        public string ABEXCHG { get; set; }
        public string ABDUNS { get; set; }
        public string ABCLASS01 { get; set; }
        public string ABCLASS02 { get; set; }
        public string ABCLASS03 { get; set; }
        public string ABCLASS04 { get; set; }
        public string ABCLASS05 { get; set; }
        public Nullable<double> ABNOE { get; set; }
        public Nullable<double> ABGROWTHR { get; set; }
        public string ABYEARSTAR { get; set; }
        public string ABAEMPGP { get; set; }
        public string ABACTIN { get; set; }
        public string ABREVRNG { get; set; }
        public Nullable<double> ABSYNCS { get; set; }
        public Nullable<double> ABPERRS { get; set; }
        public Nullable<double> ABCAAD { get; set; }
    }
}
