//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rollout.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0101Z2
    {
        public string SZEDUS { get; set; }
        public string SZEDBT { get; set; }
        public string SZEDTN { get; set; }
        public double SZEDLN { get; set; }
        public string SZEDCT { get; set; }
        public string SZTYTN { get; set; }
        public string SZEDFT { get; set; }
        public Nullable<decimal> SZEDDT { get; set; }
        public string SZDRIN { get; set; }
        public Nullable<double> SZEDDL { get; set; }
        public string SZEDSP { get; set; }
        public string SZPNID { get; set; }
        public string SZTNAC { get; set; }
        public Nullable<double> SZAN8 { get; set; }
        public string SZALKY { get; set; }
        public string SZTAX { get; set; }
        public string SZALPH { get; set; }
        public string SZDC { get; set; }
        public string SZMCU { get; set; }
        public string SZSIC { get; set; }
        public string SZLNGP { get; set; }
        public string SZAT1 { get; set; }
        public string SZCM { get; set; }
        public string SZTAXC { get; set; }
        public string SZAT2 { get; set; }
        public string SZAT3 { get; set; }
        public string SZAT4 { get; set; }
        public string SZATR { get; set; }
        public string SZAT5 { get; set; }
        public string SZATP { get; set; }
        public string SZATPR { get; set; }
        public string SZAB3 { get; set; }
        public string SZATE { get; set; }
        public string SZSBLI { get; set; }
        public Nullable<decimal> SZEFTB { get; set; }
        public Nullable<double> SZAN81 { get; set; }
        public Nullable<double> SZAN82 { get; set; }
        public Nullable<double> SZAN83 { get; set; }
        public Nullable<double> SZAN84 { get; set; }
        public Nullable<double> SZAN86 { get; set; }
        public Nullable<double> SZAN85 { get; set; }
        public string SZAC01 { get; set; }
        public string SZAC02 { get; set; }
        public string SZAC03 { get; set; }
        public string SZAC04 { get; set; }
        public string SZAC05 { get; set; }
        public string SZAC06 { get; set; }
        public string SZAC07 { get; set; }
        public string SZAC08 { get; set; }
        public string SZAC09 { get; set; }
        public string SZAC10 { get; set; }
        public string SZAC11 { get; set; }
        public string SZAC12 { get; set; }
        public string SZAC13 { get; set; }
        public string SZAC14 { get; set; }
        public string SZAC15 { get; set; }
        public string SZAC16 { get; set; }
        public string SZAC17 { get; set; }
        public string SZAC18 { get; set; }
        public string SZAC19 { get; set; }
        public string SZAC20 { get; set; }
        public string SZAC21 { get; set; }
        public string SZAC22 { get; set; }
        public string SZAC23 { get; set; }
        public string SZAC24 { get; set; }
        public string SZAC25 { get; set; }
        public string SZAC26 { get; set; }
        public string SZAC27 { get; set; }
        public string SZAC28 { get; set; }
        public string SZAC29 { get; set; }
        public string SZAC30 { get; set; }
        public string SZGLBA { get; set; }
        public Nullable<double> SZPTI { get; set; }
        public Nullable<decimal> SZPDI { get; set; }
        public string SZMSGA { get; set; }
        public string SZRMK { get; set; }
        public string SZTXCT { get; set; }
        public string SZTX2 { get; set; }
        public string SZALP1 { get; set; }
        public string SZURCD { get; set; }
        public Nullable<decimal> SZURDT { get; set; }
        public Nullable<double> SZURAT { get; set; }
        public Nullable<double> SZURAB { get; set; }
        public string SZURRF { get; set; }
        public string SZMLNM { get; set; }
        public string SZMLN1 { get; set; }
        public string SZADD1 { get; set; }
        public string SZADD2 { get; set; }
        public string SZADD3 { get; set; }
        public string SZADD4 { get; set; }
        public string SZADDZ { get; set; }
        public string SZCTY1 { get; set; }
        public string SZCTR { get; set; }
        public string SZADDS { get; set; }
        public string SZCOUN { get; set; }
        public string SZAR1 { get; set; }
        public string SZPH1 { get; set; }
        public string SZPHT1 { get; set; }
        public string SZAR2 { get; set; }
        public string SZPH2 { get; set; }
        public string SZPHT2 { get; set; }
        public string SZTORG { get; set; }
        public string SZUSER { get; set; }
        public string SZPID { get; set; }
        public string SZJOBN { get; set; }
        public Nullable<decimal> SZUPMJ { get; set; }
        public Nullable<double> SZTDAY { get; set; }
        public Nullable<double> SZUPMT { get; set; }
        public string SZPRGF { get; set; }
        public string SZSCCLTP { get; set; }
        public Nullable<double> SZPA8 { get; set; }
        public string SZTICKER { get; set; }
        public string SZEXCHG { get; set; }
        public string SZDUNS { get; set; }
        public string SZCLASS01 { get; set; }
        public string SZCLASS02 { get; set; }
        public string SZCLASS03 { get; set; }
        public string SZCLASS04 { get; set; }
        public string SZCLASS05 { get; set; }
        public Nullable<double> SZNOE { get; set; }
        public Nullable<double> SZGROWTHR { get; set; }
        public string SZYEARSTAR { get; set; }
        public string SZAEMPGP { get; set; }
        public string SZACTIN { get; set; }
        public string SZREVRNG { get; set; }
    }
}
