//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rollout.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0111Z1
    {
        public string BWEDUS { get; set; }
        public string BWEDBT { get; set; }
        public string BWEDTN { get; set; }
        public double BWEDLN { get; set; }
        public string BWEDCT { get; set; }
        public string BWTYTN { get; set; }
        public string BWEDFT { get; set; }
        public Nullable<decimal> BWEDDT { get; set; }
        public string BWDRIN { get; set; }
        public Nullable<double> BWEDDL { get; set; }
        public string BWEDSP { get; set; }
        public string BWPNID { get; set; }
        public string BWTNAC { get; set; }
        public Nullable<double> BWAN8 { get; set; }
        public Nullable<double> BWIDLN { get; set; }
        public Nullable<double> BWDSS5 { get; set; }
        public string BWMLNM { get; set; }
        public string BWATTL { get; set; }
        public string BWREM1 { get; set; }
        public string BWSLNM { get; set; }
        public string BWALPH { get; set; }
        public string BWDC { get; set; }
        public string BWGNNM { get; set; }
        public string BWMDNM { get; set; }
        public string BWSRNM { get; set; }
        public string BWTYC { get; set; }
        public string BWW001 { get; set; }
        public string BWW002 { get; set; }
        public string BWW003 { get; set; }
        public string BWW004 { get; set; }
        public string BWW005 { get; set; }
        public string BWW006 { get; set; }
        public string BWW007 { get; set; }
        public string BWW008 { get; set; }
        public string BWW009 { get; set; }
        public string BWW010 { get; set; }
        public string BWMLN1 { get; set; }
        public string BWALP1 { get; set; }
        public string BWTORG { get; set; }
        public string BWUSER { get; set; }
        public string BWPID { get; set; }
        public Nullable<decimal> BWUPMJ { get; set; }
        public string BWJOBN { get; set; }
        public Nullable<double> BWTDAY { get; set; }
        public Nullable<double> BWUPMT { get; set; }
        public string BWWN001 { get; set; }
        public string BWWN002 { get; set; }
        public string BWWN003 { get; set; }
        public string BWWN004 { get; set; }
        public string BWWN005 { get; set; }
        public string BWWN006 { get; set; }
        public string BWWN007 { get; set; }
        public string BWWN008 { get; set; }
        public string BWWN009 { get; set; }
        public string BWWN010 { get; set; }
        public string BWNICK { get; set; }
        public string BWGEND { get; set; }
        public string BWNTYP { get; set; }
        public Nullable<double> BWDDATE { get; set; }
        public Nullable<double> BWDMON { get; set; }
        public Nullable<double> BWDYR { get; set; }
        public string BWFUCO { get; set; }
        public string BWPCM { get; set; }
        public string BWPCF { get; set; }
        public string BWACTIN { get; set; }
        public string BWCFRGUID { get; set; }
        public string BWREFNAME { get; set; }
        public string BWCHPROC { get; set; }
    }
}
