//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rollout.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0117
    {
        public string A8ADDZ { get; set; }
        public string A8ADDS { get; set; }
        public string A8CTY1 { get; set; }
        public string A8COUN { get; set; }
        public string A8CTR { get; set; }
        public string A8CRTE { get; set; }
        public string A8BKML { get; set; }
        public string A8ADZ1 { get; set; }
        public string A8USER { get; set; }
        public string A8PID { get; set; }
        public Nullable<decimal> A8UPMJ { get; set; }
        public Nullable<double> A8UPMT { get; set; }
        public string A8MKEY { get; set; }
    }
}
