//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rollout.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class F4008
    {
        public string TATXA1 { get; set; }
        public string TATAXA { get; set; }
        public Nullable<double> TATA1 { get; set; }
        public Nullable<double> TATXR1 { get; set; }
        public Nullable<double> TATA2 { get; set; }
        public Nullable<double> TATXR2 { get; set; }
        public Nullable<double> TATA3 { get; set; }
        public Nullable<double> TATXR3 { get; set; }
        public Nullable<double> TATA4 { get; set; }
        public Nullable<double> TATXR4 { get; set; }
        public Nullable<double> TATA5 { get; set; }
        public Nullable<double> TATXR5 { get; set; }
        public decimal TAEFDJ { get; set; }
        public Nullable<decimal> TAEFTJ { get; set; }
        public string TAGL01 { get; set; }
        public string TAGL02 { get; set; }
        public string TAGL03 { get; set; }
        public string TAGL04 { get; set; }
        public string TAGL05 { get; set; }
        public double TAITM { get; set; }
        public string TALITM { get; set; }
        public string TAAITM { get; set; }
        public string TAUOM { get; set; }
        public string TAFVTY { get; set; }
        public Nullable<double> TAMTAX { get; set; }
        public string TATC1 { get; set; }
        public string TATC2 { get; set; }
        public string TATC3 { get; set; }
        public string TATC4 { get; set; }
        public string TATC5 { get; set; }
        public string TATT1 { get; set; }
        public string TATT2 { get; set; }
        public string TATT3 { get; set; }
        public string TATT4 { get; set; }
        public string TATT5 { get; set; }
    }
}
