//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rollout.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class F4111
    {
        public Nullable<double> ILNLIN { get; set; }
        public Nullable<double> ILITM { get; set; }
        public string ILLITM { get; set; }
        public string ILAITM { get; set; }
        public string ILMCU { get; set; }
        public string ILLOCN { get; set; }
        public string ILLOTN { get; set; }
        public string ILPLOT { get; set; }
        public Nullable<double> ILSTUN { get; set; }
        public Nullable<double> ILLDSQ { get; set; }
        public Nullable<double> ILTRNO { get; set; }
        public string ILFRTO { get; set; }
        public string ILLMCX { get; set; }
        public string ILLOTS { get; set; }
        public Nullable<double> ILLOTP { get; set; }
        public string ILLOTG { get; set; }
        public Nullable<double> ILKIT { get; set; }
        public string ILMMCU { get; set; }
        public string ILDMCT { get; set; }
        public Nullable<double> ILDMCS { get; set; }
        public string ILKCO { get; set; }
        public Nullable<double> ILDOC { get; set; }
        public string ILDCT { get; set; }
        public string ILSFX { get; set; }
        public Nullable<double> ILJELN { get; set; }
        public Nullable<double> ILICU { get; set; }
        public Nullable<decimal> ILDGL { get; set; }
        public string ILGLPT { get; set; }
        public string ILDCTO { get; set; }
        public Nullable<double> ILDOCO { get; set; }
        public string ILKCOO { get; set; }
        public Nullable<double> ILLNID { get; set; }
        public string ILIPCD { get; set; }
        public Nullable<decimal> ILTRDJ { get; set; }
        public string ILTRUM { get; set; }
        public Nullable<double> ILAN8 { get; set; }
        public string ILTREX { get; set; }
        public string ILTREF { get; set; }
        public string ILRCD { get; set; }
        public Nullable<double> ILTRQT { get; set; }
        public Nullable<double> ILUNCS { get; set; }
        public Nullable<double> ILPAID { get; set; }
        public string ILTERM { get; set; }
        public double ILUKID { get; set; }
        public Nullable<double> ILTDAY { get; set; }
        public string ILUSER { get; set; }
        public string ILPID { get; set; }
        public Nullable<decimal> ILCRDJ { get; set; }
        public string ILAID { get; set; }
        public string ILASID { get; set; }
        public string ILMCUZ { get; set; }
        public string ILOBJ { get; set; }
        public string ILSBL { get; set; }
        public string ILSUB { get; set; }
        public string ILUOM2 { get; set; }
        public string ILCMOO { get; set; }
        public string ILRE { get; set; }
        public string ILSBLT { get; set; }
        public Nullable<double> ILSQOR { get; set; }
        public Nullable<decimal> ILVPEJ { get; set; }
        public Nullable<decimal> ILHDGJ { get; set; }
        public Nullable<double> ILSHAN { get; set; }
        public Nullable<double> ILOPSQ { get; set; }
        public Nullable<double> ILRFLN { get; set; }
        public Nullable<double> ILTGN { get; set; }
        public string ILLOTC { get; set; }
        public Nullable<decimal> ILSVDT { get; set; }
        public string ILLRCD { get; set; }
        public string ILRLOT { get; set; }
        public string ILLPNU { get; set; }
        public string ILPMPN { get; set; }
        public Nullable<double> ILPNS { get; set; }
    }
}
