//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rollout.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class F4217
    {
        public double XISHPN { get; set; }
        public double XIRSSN { get; set; }
        public double XISQNR { get; set; }
        public string XIREFQ { get; set; }
        public string XIREFN { get; set; }
        public Nullable<double> XIDOC { get; set; }
        public string XIDCT { get; set; }
        public string XIKCO { get; set; }
        public string XIUSER { get; set; }
        public string XIPID { get; set; }
        public string XIJOBN { get; set; }
        public Nullable<decimal> XIUPMJ { get; set; }
        public Nullable<double> XITDAY { get; set; }
    }
}
