//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rollout.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class F4714
    {
        public string ZTEDTY { get; set; }
        public Nullable<double> ZTEDSQ { get; set; }
        public string ZTEKCO { get; set; }
        public double ZTEDOC { get; set; }
        public string ZTEDCT { get; set; }
        public double ZTEDLN { get; set; }
        public string ZTEDSP { get; set; }
        public string ZTEDBT { get; set; }
        public string ZTFILE { get; set; }
        public string ZTKCOO { get; set; }
        public Nullable<double> ZTDOCO { get; set; }
        public string ZTDCTO { get; set; }
        public Nullable<double> ZTLNID { get; set; }
        public string ZTPNTC { get; set; }
        public double ZTLINS { get; set; }
        public string ZTTXLN { get; set; }
        public string ZTTORG { get; set; }
        public string ZTUSER { get; set; }
        public string ZTPID { get; set; }
        public string ZTJOBN { get; set; }
        public Nullable<decimal> ZTUPMJ { get; set; }
        public Nullable<double> ZTTDAY { get; set; }
    }
}
