//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rollout.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class F4715
    {
        public string ZDEDTY { get; set; }
        public Nullable<double> ZDEDSQ { get; set; }
        public string ZDEKCO { get; set; }
        public double ZDEDOC { get; set; }
        public string ZDEDCT { get; set; }
        public double ZDEDLN { get; set; }
        public string ZDEDSP { get; set; }
        public string ZDEDBT { get; set; }
        public string ZDFILE { get; set; }
        public string ZDKCOO { get; set; }
        public Nullable<double> ZDDOCO { get; set; }
        public string ZDDCTO { get; set; }
        public Nullable<double> ZDLNID { get; set; }
        public string ZDPNTC { get; set; }
        public double ZDLINS { get; set; }
        public string ZDTXLN { get; set; }
        public string ZDTORG { get; set; }
        public string ZDUSER { get; set; }
        public string ZDPID { get; set; }
        public string ZDJOBN { get; set; }
        public Nullable<decimal> ZDUPMJ { get; set; }
        public Nullable<double> ZDTDAY { get; set; }
    }
}
