//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rollout.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class F4943
    {
        public double SPSHPN { get; set; }
        public double SPRSSN { get; set; }
        public double SPOSEQ { get; set; }
        public string SPEQTY { get; set; }
        public Nullable<double> SPLGTS { get; set; }
        public Nullable<double> SPWTHS { get; set; }
        public Nullable<double> SPHGTS { get; set; }
        public Nullable<double> SPGTHS { get; set; }
        public string SPLUOM { get; set; }
        public Nullable<double> SPGWEI { get; set; }
        public Nullable<double> SPWTEM { get; set; }
        public string SPWTUM { get; set; }
        public Nullable<double> SPVCUD { get; set; }
        public string SPCVUM { get; set; }
        public string SPCNID { get; set; }
        public string SPPLT { get; set; }
        public string SPREFQ { get; set; }
        public string SPREFN { get; set; }
        public string SPURCD { get; set; }
        public Nullable<decimal> SPURDT { get; set; }
        public Nullable<double> SPURAT { get; set; }
        public Nullable<double> SPURAB { get; set; }
        public string SPURRF { get; set; }
        public string SPUSER { get; set; }
        public string SPPID { get; set; }
        public string SPJOBN { get; set; }
        public Nullable<decimal> SPUPMJ { get; set; }
        public Nullable<double> SPTDAY { get; set; }
    }
}
