//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rollout.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JDEEntities : DbContext
    {
        public JDEEntities()
            : base("name=JDEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<F0101> F0101 { get; set; }
        public virtual DbSet<F03012> F03012 { get; set; }
        public virtual DbSet<F4102> F4102 { get; set; }
        public virtual DbSet<F47011> F47011 { get; set; }
        public virtual DbSet<F47012> F47012 { get; set; }
        public virtual DbSet<F4714> F4714 { get; set; }
        public virtual DbSet<F4715> F4715 { get; set; }
        public virtual DbSet<F0101Z2> F0101Z2 { get; set; }
        public virtual DbSet<F03012Z1> F03012Z1 { get; set; }
    }
}
